# Generated by Django 2.2.2 on 2019-06-14 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(blank=True, choices=[(1, 'NORMAL USER'), (2, 'ADMIN')], null=True)),
                ('user_year', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField()),
                ('venue', models.CharField(default='IMG Lab', max_length=30)),
                ('meeting_choice', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='schedule.UserProfile')),
                ('invitees', models.ManyToManyField(related_name='matchinvitees', to='schedule.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post', models.TextField(max_length=200, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('comment_user', models.TextField(max_length=20, null=True)),
                ('comment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='schedule.Meeting')),
            ],
        ),
    ]
