# Generated by Django 2.2.3 on 2019-07-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190730_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='schedule.UserProfile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invitees',
            field=models.ManyToManyField(related_name='matchinvitees', to='schedule.UserProfile'),
        ),
    ]
