# Generated by Django 2.2.1 on 2019-06-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190603_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField()),
                ('venue', models.CharField(default='IMG Lab', max_length=30)),
                ('meeting_choice', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='schedule.UserProfile')),
                ('invitees', models.ManyToManyField(to='schedule.UserProfile')),
            ],
        ),
    ]
