# Generated by Django 2.2.1 on 2019-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='invitees',
            field=models.ManyToManyField(related_name='matchinvitees', to='schedule.UserProfile'),
        ),
    ]
