# Generated by Django 2.2.1 on 2019-06-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190601_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role',
        ),
    ]
