# Generated by Django 2.2.1 on 2019-06-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190601_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.IntegerField(blank=True, choices=[(1, 'NORMAL USER'), (2, 'ADMIN')], null=True),
        ),
    ]
